// export default {
//   ADD_RANDOM_FAVORITE_JOKE: 'ADD_RANDOM_FAVORITE_JOKE',
//   ADD_FAVORITE_JOKE_BY_CATEGORY: 'ADD_FAVORITE_JOKE_BY_CATEGORY',
//   EDIT_JOKE: 'EDIT_JOKE',
//   DELETE_JOKE: 'DELETE_JOKE' 
// };